Slicer --python-script main.py \
--no-main-window \
--show-python-interactor \
--additional-module-path modules \
--modules-to-ignore \
"ACPCTransform,\
AddManyMarkupsFiducialTest,\
AddScalarVolumes,\
AddStorableDataAfterSceneViewTest,\
SubjectHierarchy,\
Annotations,\
AtlasTests,\
BRAINSDWICleanup,\
BRAINSDemonWarp,\
BRAINSFit,\
BRAINSFitRigidRegistrationCrashIssue4139,\
BRAINSLabelStats,\
BRAINSROIAuto,\
BRAINSResample,\
BRAINSResize,\
BRAINSStripRotation,\
BRAINSTransformConvert,\
Cameras,\
CastScalarVolume,\
Charting,\
CheckerBoardFilter,\
Colors,\
ColorsScalarBarSelfTest,\
CompareVolumes,\
CreateDICOMSeries,\
Units,\
Volumes,\
ResampleScalarVectorDWIVolume,\
CropVolume,\
CropVolumeSelfTest,\
CurvatureAnisotropicDiffusion,\
DICOM,\
DICOMPatcher,\
DICOMScalarVolumePlugin,\
DICOMSlicerDataBundlePlugin,\
DMRIInstall,\
DWIConvert,\
Data,\
DataProbe,\
DataStore,\
DoubleArrays,\
EMSegment,\
EMSegmentCommandLine,\
EMSegmentQuick,\
EMSegmentTransformToNewFormat,\
Editor,\
Endoscopy,\
EventBroker,\
ExecutionModelTour,\
ExpertAutomatedRegistration,\
ExtensionWizard,\
ExtractSkeleton,\
FiducialLayoutSwitchBug1914,\
FiducialRegistration,\
GaussianBlurImageFilter,\
GradientAnisotropicDiffusion,\
GrayscaleFillHoleImageFilter,\
GrayscaleGrindPeakImageFilter,\
GrayscaleModelMaker,\
HistogramMatching,\
ImageLabelCombine,\
IslandRemoval,\
JRC2013Vis,\
LabelMapSmoothing,\
LabelStatistics,\
LandmarkRegistration,\
Markups,\
MarkupsInCompareViewersSelfTest,\
MarkupsInViewsSelfTest,\
MarkupsWidgetsSelfTest,\
MaskScalarVolume,\
MedianImageFilter,\
MergeModels,\
ModelMaker,\
ModelToLabelMap,\
Models,\
MultiVolumeExplorer,\
MultiVolumeImporter,\
MultiVolumeImporterPlugin,\
MultiplyScalarVolumes,\
N4ITKBiasFieldCorrection,\
NeurosurgicalPlanningTutorialMarkupsSelfTest,\
OpenIGTLinkIF,\
OrientScalarVolume,\
OtsuThresholdImageFilter,\
PETStandardUptakeValueComputation,\
PerformMetricTest,\
PerformanceTests,\
ProbeVolumeWithModel,\
RSNA2012ProstateDemo,\
RSNAQuantTutorial,\
RSNAVisTutorial,\
Reformat,\
ResampleDTIVolume,\
ResampleScalarVolume,\
RobustStatisticsSegmenter,\
SampleData,\
ScenePerformance,\
SceneViews,\
ScreenCapture,\
Segmentations,\
SegmentEditor,\
SegmentStatistics,\
SelfTests,\
SimpleFilters,\
SimpleRegionGrowingSegmentation,\
SliceLinkLogic,\
Slicer4Minute,\
SlicerBoundsTest,\
SlicerMRBMultipleSaveRestoreLoopTest,\
SlicerMRBMultipleSaveRestoreTest,\
SlicerMRBSaveRestoreCheckPathsTest,\
SlicerOrientationSelectorTest,\
SlicerTransformInteractionTest1,\
SubjectHierarchyCorePluginsSelfTest,\
SubjectHierarchyGenericSelfTest,\
SubtractScalarVolumes,\
SurfaceToolbox,\
Tables,\
TablesSelfTest,\
Terminologies,\
ThresholdScalarVolume,\
ThresholdThreadingTest,\
Transforms,\
UtilTest,\
VBRAINSDemonWarp,\
VectorToScalarVolume,\
ViewControllers,\
ViewControllersSliceInterpolationBug1926,\
VolumeRendering,\
VolumeRenderingSceneClose,\
VotingBinaryHoleFillingImageFilter,\
Welcome,\
sceneImport2428,\
slicerCloseCrashBug2590"